export type Lang = 'ar' | 'en';
export type Text = { ar: string; en: string };
export const text = (ar: string, en: string): Text => ({ ar, en });
export const profile = {
  name: 'Ahmed Alaa',
  email: 'a.alaahamoda@gmail.com',
  phone: '+20 109 493 8005',
  phoneLink: '+201094938005',
  linkedin: 'https://www.linkedin.com/in/ahmed-alaa-764b44407',
  cv: './assets/Ahmed-Alaa-CV.pdf',
  location: text('العاشر من رمضان، الشرقية، مصر', '10th of Ramadan, Sharkia, Egypt'),
};
export const ui = {
  skip: text('انتقل إلى المحتوى', 'Skip to content'),
  portfolio: text('البورتفوليو المهني', 'Professional portfolio'),
  nav: [
    { id: 'about', label: text('نبذة عني', 'About') },
    { id: 'work', label: text('أعمالي', 'My work') },
    { id: 'digital', label: text('التحول الرقمي', 'Digital transformation') },
    { id: 'experience', label: text('الخبرات', 'Experience') },
    { id: 'skills', label: text('المهارات', 'Skills') },
    { id: 'learning', label: text('التعليم والكورسات', 'Education & courses') },
  ],
  menu: text('فتح قائمة التنقل', 'Open navigation menu'),
  closeMenu: text('إغلاق القائمة', 'Close navigation menu'),
  contact: text('تواصل معي', 'Contact me'),
  title: text('مدير مخازن وخدمات لوجستية', 'Warehouse & Logistics Manager'),
  intro: text('أربط خبرتي في إدارة المخازن وSAP بتحليل البيانات والأتمتة؛ وأحوّل احتياجات العمل إلى برامج وأدوات عملية تدعم دقة المخزون وكفاءة العمليات واتخاذ القرار.', 'I connect hands-on warehouse management and SAP experience with data analysis and automation, turning operational needs into practical software and tools that support inventory accuracy, efficient operations and informed decisions.'),
  specialties: text('SAP MM / EWM / SD | مراقبة المخزون | أتمتة التقارير | رقمنة المخازن', 'SAP MM / EWM / SD | Inventory Control | Reporting Automation | Warehouse Digitization'),
  browse: text('استعراض أعمالي', 'Explore my work'),
  download: text('تحميل السيرة الذاتية', 'Download CV'),
  portrait: text('الصورة الشخصية لأحمد علاء', 'Portrait of Ahmed Alaa'),
  years: text('سنوات من الخبرة التشغيلية', 'Years of operational experience'),
  sites: text('مواقع للعمليات المخزنية', 'Warehouse operational sites'),
  sap: text('خبرة عملية وتكامل بين العمليات', 'Hands-on expertise & process integration'),
  practical: text('خبرة ميدانية تتحول إلى حلول', 'Operational experience, put to work'),
  about: text('إدارة المخازن برؤية أوسع.', 'Warehouse management. A wider perspective.'),
  aboutIntro: text('لدي خبرة تتجاوز 10 سنوات في إدارة المخازن والخدمات اللوجستية، وأدير العمليات عبر 5+ مواقع. أعمل في مؤسسة الإيمان منذ 2016، وتدرّجت من أمين مخزن إلى مشرف ثم مدير مخازن. أجمع بين إدارة العمليات والرقابة على المخزون وتطوير الإجراءات والأدوات الرقمية.', 'With 10+ years in warehouse and logistics operations, I manage operations across 5+ sites. At Aleman Foundation since 2016, I have progressed from Storekeeper to Warehouse Supervisor and Warehouse Manager. My experience combines daily operations, inventory control, better processes and practical digital tools.'),
  aboutFocus: text('أستخدم SAP MM وEWM وSD، مع التنسيق مع PP وPM وFI لربط المخازن بالمشتريات والإنتاج والصيانة والمالية. وأطوّر تقارير ولوحات متابعة باستخدام Excel وGoogle Sheets وVBA لدعم وضوح البيانات والقرار.', 'I work with SAP MM, EWM and SD, coordinating with PP, PM and FI to connect warehouse, procurement, production, maintenance and finance operations. I develop reports and dashboards with Excel, Google Sheets and VBA to make data clearer and decisions better informed.'),
  aboutGbs: text('أقود حاليًا مشروع Global Barcode Solutions (GBS)، من التنسيق مع المورد والتعاقد إلى التنفيذ وإطلاق النظام.', 'I am currently leading the Global Barcode Solutions (GBS) project, from vendor alignment and contracting through implementation and system rollout.'),
  seeGbs: text('مشروع GBS', 'The GBS project'),
  focus: [text('دقة المخزون والرقابة', 'Inventory accuracy & control'), text('تكامل العمليات عبر SAP', 'Connected SAP processes'), text('تحسين الإجراءات والأتمتة', 'Process improvement & automation')],
  workEyebrow: text('برامج طوّرتها لخدمة العمل', 'Software built around real operations'),
  workTitle: text('احتياج عملي. حل رقمي.', 'A real need. A practical solution.'),
  workIntro: text('برنامجان يجسّدان تحويل احتياجات التشغيل إلى شاشات متابعة وتوثيق وتقارير. استعرض وظائفهما ولقطات من الواجهات الفعلية.', 'Two systems that turn operational needs into monitoring, documentation and reporting workflows. Explore their functions and screenshots from the actual interfaces.'),
  details: text('تفاصيل المشروع', 'Project details'),
  role: text('دوري', 'My contribution'),
  need: text('احتياج العمل', 'Operational need'),
  functions: text('الوظائف الرئيسية', 'Main functions'),
  workflow: text('دورة العمل', 'Workflow'),
  value: text('الفائدة التشغيلية', 'Operational value'),
  gallery: text('معرض الشاشات', 'Screen gallery'),
  openGallery: text('استعراض الشاشات', 'Explore screenshots'),
  screens: text('لقطة شاشة', 'screenshots'),
  enlarge: text('تكبير الصورة', 'Enlarge image'),
  previous: text('الصورة السابقة', 'Previous image'),
  next: text('الصورة التالية', 'Next image'),
  close: text('إغلاق المعرض', 'Close gallery'),
  zoom: text('عرض بالحجم الأصلي', 'View at original size'),
  fit: text('ملاءمة الصورة للشاشة', 'Fit image to screen'),
  imageError: text('تعذّر تحميل الصورة. حاول فتحها مرة أخرى.', 'The image could not load. Try opening it again.'),
  privacy: text('حُجبت البيانات الشخصية والتشغيلية الحساسة في الصور المعروضة.', 'Personal and sensitive operational data has been redacted from these images.'),
  digitalEyebrow: text('التحول الرقمي في العمليات', 'Digital transformation in practice'),
  digitalTitle: text('من الإجراءات إلى التتبّع الرقمي.', 'From procedures to digital traceability.'),
  ongoing: text('مشروع جارٍ', 'In progress'),
  gbsSub: text('مشروع رقمنة المخازن بالباركود', 'Warehouse digitization with barcodes'),
  gbsRole: text('مدير المشروع', 'Project Manager'),
  gbsIntro: text('أقود تنفيذ Global Barcode Solutions داخل العمليات المخزنية، بهدف تحسين التتبّع ووضوح المخزون والرقابة التشغيلية.', 'I lead the implementation of Global Barcode Solutions within warehouse operations, with the goal of improving traceability, inventory visibility and operational control.'),
  gbsSteps: [
    { title: text('التنسيق مع المورد', 'Vendor alignment'), body: text('مواءمة احتياجات التشغيل مع متطلبات الحل.', 'Align operational needs with the solution requirements.') },
    { title: text('التعاقد', 'Contracting'), body: text('التنسيق والمتابعة في مرحلة التعاقد.', 'Coordinate and follow through the contracting stage.') },
    { title: text('التنفيذ', 'Implementation'), body: text('قيادة تنفيذ النظام داخل العمليات المخزنية.', 'Lead system implementation within warehouse operations.') },
    { title: text('إطلاق النظام', 'System rollout'), body: text('متابعة إطلاق الحل ضمن دورة العمل.', 'Oversee the solution rollout within the operational workflow.') },
  ],
  reportingTitle: text('تقارير أوضح. عمل يدوي أقل.', 'Clearer reporting. Less manual effort.'),
  reportingBody: text('أطوّر تقارير ولوحات متابعة آلية باستخدام Excel وGoogle Sheets وVBA لتحليل حركة المخزون والاستهلاك والأصناف السريعة والبطيئة الحركة ومؤشرات الأداء. تدعم هذه الأدوات سرعة إعداد التقارير ووضوح البيانات.', 'I develop automated reports and dashboards with Excel, Google Sheets and VBA to analyse stock movements, consumption, slow- and fast-moving items and performance indicators. These tools support faster reporting and clearer operational data.'),
  reportLink: text('شاهد مركز التقارير ضمن أعمالي', 'See the report center in my work'),
  experienceEyebrow: text('الخبرة المهنية', 'Professional experience'),
  experienceTitle: text('مسار بدأ من أرض المخزن.', 'A career built on the warehouse floor.'),
  company: text('مؤسسة الإيمان', 'Aleman Foundation'),
  current: text('الوظيفة الحالية', 'Current role'),
  skillsEyebrow: text('مجالات الخبرة', 'Areas of expertise'),
  skillsTitle: text('التشغيل والبيانات، معًا.', 'Operations and data, together.'),
  learningEyebrow: text('التعليم والتطوير المهني', 'Education & professional development'),
  learningTitle: text('خبرة عملية، وتعلّم مستمر.', 'Practical experience. Continuous learning.'),
  degree: text('بكالوريوس الاقتصاد', 'Bachelor’s Degree in Economics'),
  university: text('جامعة الزقازيق', 'Zagazig University'),
  courses: text('كورسات وشهادات تعلّم مختارة', 'Selected courses & learning certificates'),
  viewCertificate: text('عرض', 'View'),
  downloadCertificate: text('تحميل', 'Download'),
  viewCertificateLabel: text('عرض الشهادة', 'View certificate'),
  downloadCertificateLabel: text('تحميل الشهادة', 'Download certificate'),
  opensInNewTab: text('يفتح في تبويب جديد', 'Opens in a new tab'),
  completion: text('إتمام دورة', 'Course completion'),
  learningPath: text('شهادة مسار تعليمي', 'Learning path certificate'),
  hours: text('96 ساعة · 9.6 CEUs', '96 hours · 9.6 CEUs'),
  trainingNote: text('دورات SAP المعروضة تدريبية؛ لا تمثل اعتمادًا مهنيًا رسميًا من SAP.', 'The SAP courses listed are training courses, rather than official SAP professional certification.'),
  contactEyebrow: text('لنبدأ حوارًا', 'Let’s start a conversation'),
  contactTitle: text('تواصل معي.', 'Get in touch.'),
  contactBody: text('لمناقشة فرص العمل في إدارة المخازن والخدمات اللوجستية أو مشروعات تحسين العمليات والتحول الرقمي.', 'To discuss opportunities in warehouse and logistics management, process improvement or digital transformation projects.'),
  email: text('البريد الإلكتروني', 'Email'),
  phone: text('الهاتف', 'Phone'),
  linkedIn: text('الملف المهني على LinkedIn', 'Professional profile on LinkedIn'),
  location: text('الموقع', 'Location'),
  rights: text('جميع الحقوق محفوظة.', 'All rights reserved.'),
  backTop: text('العودة إلى الأعلى', 'Back to top'),
};
export const projects = [
  {
    id: 'warehouse-audit', key: 'audit', number: '01',
    name: text('WAREHOUSE AUDIT SYSTEM', 'WAREHOUSE AUDIT SYSTEM'),
    category: text('مراجعة المخزون والتقارير', 'Inventory review & reporting'),
    operationalUse: text('يعمل حاليًا بكفاءة عالية في ٣ مصانع لإنتاج الأعلاف.', 'Currently running with high efficiency across 3 animal feed plants.'),
    summary: text('برنامج يجمع مراجعة الحركات المخزنية والجرد والتوثيق والتقارير في واجهة واحدة، مع شاشات متابعة تناسب الكمبيوتر والهاتف.', 'A system bringing stock movement review, inventory auditing, documentation and reporting into one interface, with desktop and mobile views.'),
    need: text("برنامج طوّرته لدعم مراجعة عمليات المخازن، من رفع التقارير ومتابعة الحركات إلى توثيق الجرد وعرض الملخصات الإدارية. يجمع وظائف المراجعة في واجهة واحدة، مع فلاتر تساعد على الوصول إلى البيانات حسب التاريخ والموقع والمادة. يخدم الحاجة إلى قراءة تقارير المبيعات والتحويلات والوارد والخامات بصورة مترابطة، ومراجعة الكميات والفروق، ثم تقديم المعلومات بصورة أوضح للمتابعة واتخاذ القرار.", "I developed this program to support warehouse operations review, from uploading reports and examining movements to documenting inventory counts and presenting management summaries. It brings review functions into one interface, with filters for date, site and material. It addresses the need to examine sales, transfers, receipts and material reports together, review quantities and differences, and present information more clearly for operational monitoring and decisions."),
    role: text("حوّلت احتياجات العمل في إدارة المخازن إلى شاشات عملية لرفع البيانات ومراجعتها وتوثيقها وإعداد التقارير. طوّرت البرنامج خطوة بخطوة، مع تحسين عرض النتائج، وأدوات التصدير، وإعدادات المستخدمين والنظام وفق احتياجات التشغيل.", "I translated warehouse management needs into practical screens for uploading, reviewing and documenting data and preparing reports. I developed the program step by step, improving results presentation, export tools, and user and system settings around operational requirements."),
    features: [
      { title: text("رفع التقارير", "Report uploads"), body: text("اختيار نوع التقرير وتاريخه ورفع ملفات Excel، مع سجل للملفات المرفوعة وخيارات عرضها واستبدالها وحذفها.", "Select a report type and date, upload Excel files, and review an upload history with options to view, replace or delete files.") },
      { title: text("مراجعة الحركات", "Movement review"), body: text("شاشات لمراجعة المبيعات والتحويلات والوارد ومتابعة الخامات واستهلاكها، مع البحث والتصفية ووضع التركيز.", "Review sales, transfers and receipts, and track materials and consumption, with search, filters and a focus mode.") },
      { title: text("الجرد والتوثيق", "Inventory documentation"), body: text("شاشات لمستندات الجرد وتوثيق العدّ ومراجعة الكميات والفروق، مع أدوات متابعة تواريخ الإنتاج.", "Use inventory documents and count documentation to review quantities and differences, alongside production-date tracking tools.") },
      { title: text("المتابعة الإدارية", "Management monitoring"), body: text("لوحة مؤشرات ورسوم وملخصات تنفيذية حسب التاريخ والموقع والمادة، مع شاشات لإدارة القسم وأعماله وتقاريره.", "Use dashboard charts and executive summaries by date, site and material, alongside screens for department administration, activities and reports.") },
      { title: text("التصدير والتنظيم", "Exports and administration"), body: text("تصدير التقارير بصيغ Excel وPDF وPNG في الشاشات التي توفرها، وإدارة المستخدمين والأدوار وشاشات الصلاحيات والإعدادات وسجل النشاط.", "Export Excel, PDF and PNG reports where available, and manage users, roles, permission screens, settings and the activity log.") },
      { title: text("واجهات الكمبيوتر والهاتف", "Desktop & mobile views"), body: text("شاشات للكمبيوتر والهاتف، مع واجهات بمظهر فاتح وداكن.", "Desktop and mobile screens, with light and dark appearances.") },
    ],
    workflow: [
      { title: text("تحديد التقرير", "Select the report"), body: text("يختار المستخدم نوع التقرير والفترة أو تاريخ التقرير المناسب للمراجعة.", "Choose the report type and the period or report date needed for review.") },
      { title: text("رفع البيانات", "Upload the data"), body: text("يرفع ملف Excel من شاشة رفع التقارير، ويستطيع الرجوع إلى سجل الملفات لمراجعة ما تم رفعه أو استبداله عند الحاجة.", "Upload an Excel file through the report upload screen. Use the upload history to review uploaded files or replace them when needed.") },
      { title: text("مراجعة الحركات", "Review movements"), body: text("يفتح شاشة المبيعات والتحويلات أو الوارد أو متابعة الخامات، ويستخدم فلاتر الموقع والمادة والتاريخ للوصول إلى نطاق المراجعة المطلوب.", "Open sales and transfers, receipts or material tracking, and filter by site, material and date to focus the review.") },
      { title: text("توثيق الجرد", "Document inventory counts"), body: text("ينتقل إلى شاشات الجرد لتسجيل العدّ ومراجعة الكميات والفروق وتوثيق المراجعة.", "Use the inventory screens to record counts, review quantities and differences, and document the review.") },
      { title: text("قراءة الملخصات", "Read the summaries"), body: text("يستخدم لوحة المؤشرات والتقارير التنفيذية للاطلاع على الملخصات والرسوم ومقارنة البيانات بين المواقع التي تظهر في التقارير.", "Use the dashboard and executive reports to review summaries and charts and compare data across the sites represented in the reports.") },
      { title: text("إخراج التقرير", "Export the report"), body: text("يصدّر النتائج بالصيغة المتاحة في الشاشة لمشاركتها أو الاحتفاظ بها كمرجع للمراجعة.", "Export results in a format offered by the screen, for sharing or retaining as a review reference.") },
    ],
    galleryIntro: text("توضح لقطات البرنامج شاشات رفع التقارير والمراجعة والجرد ولوحات المتابعة والتقارير والإدارة، مع أمثلة لعرض الواجهة على الكمبيوتر والهاتف.", "The screenshots cover report uploads, review, inventory, dashboards, reports and administration, with examples of the interface on desktop and mobile."),
    value: text("يساعد البرنامج على تنظيم مراجعة الحركات والجرد داخل مسار واضح، وإظهار البيانات والفروق بصورة أسهل للمتابعة. وتدعم الفلاتر والتقارير والتصدير الرقابة التشغيلية والتواصل الإداري واتخاذ القرار.", "The program helps organise movement and inventory review into a clear workflow and makes data and differences easier to monitor. Filters, reports and exports support operational control, management communication and decisions."),
    preview: './assets/audit-02-dark.webp',
    previewCaption: text('لوحة المتابعة الرئيسية', 'Main dashboard'),
    tags: [text('الجرد والتوثيق', 'Inventory documentation'), text('لوحات متابعة', 'Dashboards'), text('تقارير وتصدير', 'Reports & exports')],
  },
  {
    id: 'custody-management', key: 'custody', number: '02',
    name: text('برنامج إدارة العهدة', 'Custody Management System'),
    category: text('تتبّع العهدة والحركات', 'Custody & movement tracking'),
    operationalUse: text('يعمل حاليًا بكفاءة عالية في ٥ مصانع.', 'Currently running with high efficiency across 5 factories.'),
    summary: text('برنامج لتوثيق صرف العهدة واستلامها، ومتابعة حالتها وحركاتها، مع شاشات للموظفين والمقاولين والتقارير.', 'A system for documenting custody issues and returns, tracking their status and movements, with workflows for employees, contractors and reporting.'),
    need: text("برنامج طوّرته لتنظيم صرف العهدة واستلامها ومتابعة حالتها، مع تسجيل بيانات المستلم والأصناف والكميات ومرجع الحركة. يجمع التكويد والصرف والاستلام والتقارير وسجل الحركات في واجهة واحدة. يخدم الحاجة إلى معرفة ما تم صرفه، ولمن صُرف، وما تم استلامه وما زال معلقًا، مع التعامل مع الموظفين المكوّدين وغير المكوّدين والمقاولين من خلال وسيط.", "I developed this program to organise the issue, return and status monitoring of items assigned to recipients, while recording recipient details, items, quantities and movement references. It brings master data, issue and return forms, reports and movement logs into one interface. It addresses the need to know what was issued, to whom, what has been returned and what remains outstanding, while supporting coded and uncoded employees and contractors through an intermediary."),
    role: text("حوّلت دورة العهدة إلى شاشات عملية تبدأ ببيانات الموظفين والأصناف، ثم تسجيل الصرف والاستلام ومتابعة الحركات. طوّرت البرنامج خطوة بخطوة، مع نماذج تناسب أنواع المستلمين، وتقارير للمراجعة، وشاشات لإدارة المستخدمين والصلاحيات.", "I translated the custody workflow into practical screens, starting with employee and item data and continuing through issue, return and movement monitoring. I developed the program step by step, with forms for different recipient types, review reports, and user and permission management screens."),
    features: [
      { title: text("التكويد والبيانات المرجعية", "Master data"), body: text("شاشة لبيانات الموظفين والأصناف، تشمل الأكواد والأسماء والأقسام والوظائف وبيانات التواصل ووصف الصنف.", "Maintain employee and item records, including codes, names, departments, job titles, contact details and item descriptions.") },
      { title: text("نماذج الصرف", "Issue forms"), body: text("مسارات للموظف المكوّد وغير المكوّد وللمقاول من خلال وسيط، مع بيانات المستلم الفعلي وأمين المخزن والتاريخ والوقت والوردية والملاحظات.", "Use separate paths for coded employees, uncoded employees and contractors through an intermediary. Record the actual recipient, storekeeper, date, time, shift and notes.") },
      { title: text("أصناف الحركة", "Movement items"), body: text("تسجيل كود الصنف ووصفه وكميته، وإضافة أكثر من صنف في نموذج الصرف الواحد.", "Record item codes, descriptions and quantities, and add multiple items within one issue form.") },
      { title: text("الاستلام والحالة", "Returns and status"), body: text("شاشة للبحث عن العهدة بحسب نوع المستلم وبياناته، وتسجيل الاستلام وملاحظاته، مع عرض حالات المستلم والمعلق في المتابعة.", "Search for assigned items by recipient type and details, record returns and notes, and monitor returned and outstanding statuses.") },
      { title: text("المتابعة والتقارير", "Monitoring and reports"), body: text("لوحة ملخصات للحركات والحالات والأصناف، وتقارير يومية وبحسب المستلمين والورديات، مع تصدير Excel وPDF وسجل حركات قابل للتصفية.", "View movement, status and item summaries; use daily, recipient and shift reports, Excel and PDF exports, and a filterable movement log.") },
      { title: text("الإدارة", "Administration"), body: text("شاشات للمستخدمين والصلاحيات، وقائمة للتنقل بين المواقع أو المصانع المعروضة في الواجهة.", "Use user and permission screens and a navigation list for the sites or factories shown in the interface.") },
    ],
    workflow: [
      { title: text("تجهيز البيانات", "Prepare master data"), body: text("تسجيل بيانات الموظفين والأصناف في شاشة التكويد لاستخدامها في تسجيل الحركات.", "Record employee and item details in the master data screen for use when recording movements.") },
      { title: text("اختيار مسار الصرف", "Choose the issue path"), body: text("اختيار الموظف المكوّد أو غير المكوّد أو المقاول من خلال وسيط، بحسب حالة المستلم.", "Select a coded employee, uncoded employee or contractor through an intermediary, according to the recipient’s circumstances.") },
      { title: text("تسجيل الحركة", "Record the movement"), body: text("إدخال بيانات المستلم الفعلي وأمين المخزن والتاريخ والوقت والوردية، ثم الأصناف والكميات والملاحظات. يمكن إضافة أكثر من صنف قبل حفظ نموذج الصرف.", "Enter the actual recipient, storekeeper, date, time and shift, followed by items, quantities and notes. Multiple items can be added before saving the issue form.") },
      { title: text("تسجيل الاستلام", "Record the return"), body: text("الانتقال إلى شاشة الاستلام، وتحديد نوع المستلم والبحث عن العهدة، ثم تسجيل الاستلام وبياناته وملاحظاته.", "Open the return screen, select the recipient type and search for the assigned items, then record the return details and notes.") },
      { title: text("متابعة الحالات", "Monitor statuses"), body: text("الرجوع إلى لوحة الملخصات والتقارير لمعرفة الحركات المستلمة والمعلقة ومتابعة النشاط بحسب المستلم أو الوردية أو الفترة.", "Use dashboard summaries and reports to follow returned and outstanding movements and review activity by recipient, shift or period.") },
      { title: text("مراجعة المرجع", "Review the reference"), body: text("استخدام سجل الحركات بفلاتر التاريخ ونوع الحركة والمستخدم، وتصدير التقارير المتاحة بصيغة Excel أو PDF عند الحاجة.", "Filter the movement log by date, movement type and user, and export available reports to Excel or PDF when needed.") },
    ],
    galleryIntro: text("توضح لقطات البرنامج لوحة المتابعة، ومسارات الصرف بحسب نوع المستلم، وشاشة الاستلام، والتقارير والتكويد وسجل الحركات وإدارة المستخدمين والصلاحيات.", "The screenshots cover the dashboard, issue paths by recipient type, the return screen, reports, master data, movement logs, and user and permission management."),
    value: text("يساعد البرنامج على توضيح العلاقة بين المستلم والأصناف والكميات وحالة العهدة، مع مرجع منظم للصرف والاستلام. وتتيح التقارير متابعة العهد المعلقة والحركات المسجلة بصورة أوضح، بما يدعم الرقابة والمتابعة اليومية.", "The program helps make the relationship between recipients, items, quantities and custody status clearer, with an organised reference for issues and returns. Reports make outstanding items and recorded movements easier to follow, supporting control and daily monitoring."),
    preview: './assets/custody-02.webp',
    previewCaption: text('لوحة المتابعة ودورة العهدة', 'Dashboard & custody workflows'),
    tags: [text('صرف واستلام', 'Issues & returns'), text('سجل الحركات', 'Movement log'), text('متابعة وتقارير', 'Tracking & reporting')],
  },
];
export const experience = [
  { period: text('مايو 2019 – حتى الآن', 'May 2019 – Present'), title: text('مدير مخازن | استشاري SAP MM (التنفيذ الداخلي)', 'Warehouse Manager | SAP MM Consultant (Internal Implementation)'), current: true,
    items: [text('إدارة الاستلام والصرف والتخزين والرقابة على المخزون عبر 5+ مواقع، وتصميم مواقع التخزين وBins وMovement Types.', 'Manage receiving, issuing, storage and inventory control across 5+ sites, with warehouse structure, bins, locations and movement types.'), text('SAP Key User لوحدات MM وEWM وSD، مع التنسيق مع PP وPM وFI ودورة المشتريات PR / PO / GR.', 'SAP Key User for MM, EWM and SD, coordinating with PP, PM and FI and the PR / PO / GR procurement cycle.'), text('قيادة الفريق، ومتابعة الجرد ومؤشرات الأداء، وتطوير التقارير والأتمتة وقيادة مشروع الباركود.', 'Lead the team, monitor inventory counts and KPIs, develop reports and automation, and lead the barcode project.')] },
  { period: text('مايو 2017 – مايو 2019', 'May 2017 – May 2019'), title: text('مشرف مخازن', 'Warehouse Supervisor'), current: false,
    items: [text('الإشراف على العمليات اليومية وتنسيق أعمال فريق المخازن وتحسين سير العمل.', 'Supervise daily warehouse operations, coordinate team activities and improve workflow.'), text('إدارة المخزون وحركاته والتقارير باستخدام Alpha.', 'Manage inventory, stock movements and reporting using Alpha.')] },
  { period: text('مايو 2016 – مايو 2017', 'May 2016 – May 2017'), title: text('أمين مخزن', 'Storekeeper'), current: false,
    items: [text('تنفيذ الاستلام والصرف وحفظ سجلات المخزون باستخدام Alpha.', 'Handle receiving and issuing, maintaining accurate stock records with Alpha.'), text('ضمان التخزين السليم والمناولة والانضباط في العمل اليومي.', 'Ensure proper storage, material handling and day-to-day warehouse discipline.')] },
];
export const skills = [
  { icon: 'warehouse', title: text('إدارة المخازن ومراقبة المخزون', 'Warehouse & inventory management'), items: text('الاستلام والصرف · الجرد الدوري · دقة الأرصدة · تخطيط المخازن وBins', 'Receiving & issuing · Cycle counting · Stock accuracy · Warehouse layout & bins') },
  { icon: 'network', title: text('SAP والتكامل بين العمليات', 'SAP & process integration'), items: text('SAP MM / EWM / SD · SAP Key User · التنسيق مع PP / PM / FI', 'SAP MM / EWM / SD · SAP Key User · PP / PM / FI coordination') },
  { icon: 'clipboard', title: text('دورة المشتريات', 'Procurement cycle'), items: text('PR / PO / GR · التنسيق مع المشتريات والمالية · توافر المواد', 'PR / PO / GR · Purchasing & finance coordination · Material availability') },
  { icon: 'chart', title: text('تحليل البيانات والتقارير', 'Data analysis & reporting'), items: text('مؤشرات الأداء · تحليل الحركة والاستهلاك · الأصناف السريعة والبطيئة الحركة', 'KPIs · Movement & consumption analysis · Slow- & fast-moving items') },
  { icon: 'sheet', title: text('Excel والأتمتة', 'Excel & automation'), items: text('Excel · Pivot Tables · Lookup Functions · Google Sheets · VBA · التحقق من البيانات', 'Excel · Pivot Tables · Lookup Functions · Google Sheets · VBA · Data validation') },
  { icon: 'code', title: text('تطوير الأدوات التشغيلية', 'Operational tools development'), items: text('تحويل احتياجات العمل إلى برامج عملية · نماذج توثيق · لوحات متابعة', 'Turn operational needs into practical software · Documentation workflows · Dashboards') },
  { icon: 'barcode', title: text('الباركود والتحول الرقمي', 'Barcode & digitization'), items: text('Global Barcode Solutions · التتبّع · وضوح المخزون · إطلاق النظام', 'Global Barcode Solutions · Traceability · Inventory visibility · System rollout') },
  { icon: 'users', title: text('القيادة وتحسين الإجراءات', 'Leadership & process improvement'), items: text('قيادة الفرق · توزيع المهام · التنسيق مع الموردين · التعاون بين الإدارات', 'Team supervision · Task allocation · Vendor coordination · Cross-functional collaboration') },
];
export type Course = { name: string; provider: string; date?: Text; type: 'path' | 'course'; hours?: boolean; certificate?: string };
export const courses: Course[] = [
  { name: 'CSCMP Supply Chain Foundations: Inventory Management Professional Certificate', provider: 'CSCMP / LinkedIn Learning', date: text('أكتوبر 2026', 'Oct 2026'), type: 'path', certificate: './assets/certificates/cscmp-inventory-management.pdf' },
  { name: 'BUS606: Operations and Supply Chain Management', provider: 'Saylor University', date: text('سبتمبر 2026', 'Sep 2026'), type: 'course', hours: true, certificate: './assets/certificates/bus606-operations-supply-chain-management.pdf' },
  { name: 'SAP Materials Management Essential Training', provider: 'LinkedIn Learning', date: text('سبتمبر 2026', 'Sep 2026'), type: 'course', certificate: './assets/certificates/sap-materials-management-essential-training.pdf' },
  { name: 'SAP S/4HANA Essential Training', provider: 'LinkedIn Learning', type: 'course', certificate: './assets/certificates/sap-s4hana-essential-training.pdf' },
  { name: 'Supply Chain Foundations: Analytics', provider: 'LinkedIn Learning', date: text('أكتوبر 2026', 'Oct 2026'), type: 'course', certificate: './assets/certificates/supply-chain-foundations-analytics.pdf' },
  { name: 'Excel Supply Chain Analysis: Solving Inventory Problems', provider: 'LinkedIn Learning', type: 'course', certificate: './assets/certificates/excel-supply-chain-inventory-problems.pdf' },
  { name: 'Inventory Management Foundations', provider: 'LinkedIn Learning', type: 'course', certificate: './assets/certificates/inventory-management-foundations.pdf' },
  { name: 'Foundations of Working Capital Management', provider: 'LinkedIn Learning', type: 'course', certificate: './assets/certificates/working-capital-management-foundations.pdf' },
];
