export type Lang = 'ar' | 'en';
export type Text = { ar: string; en: string };
export const text = (ar: string, en: string): Text => ({ ar, en });
export const profile = {
  name: 'Ahmed Alaa',
  email: 'a.alaahamoda@gmail.com',
  phone: '+20 109 493 8005',
  phoneLink: '+201094938005',
  linkedin: 'https://www.linkedin.com/in/ahmed-alaa-764b44407',
  cv: './assets/Ahmed-Alaa-CV.pdf',
  location: text('العاشر من رمضان، الشرقية، مصر', '10th of Ramadan, Sharkia, Egypt'),
};
export const ui = {
  skip: text('انتقل إلى المحتوى', 'Skip to content'),
  portfolio: text('البورتفوليو المهني', 'Professional portfolio'),
  nav: [
    { id: 'about', label: text('نبذة عني', 'About') },
    { id: 'work', label: text('أعمالي', 'My work') },
    { id: 'digital', label: text('التحول الرقمي', 'Digital transformation') },
    { id: 'experience', label: text('الخبرات', 'Experience') },
    { id: 'skills', label: text('المهارات', 'Skills') },
    { id: 'learning', label: text('التعليم والكورسات', 'Education & courses') },
  ],
  menu: text('فتح قائمة التنقل', 'Open navigation menu'),
  closeMenu: text('إغلاق القائمة', 'Close navigation menu'),
  contact: text('تواصل معي', 'Contact me'),
  title: text('مدير مخازن وخدمات لوجستية', 'Warehouse & Logistics Manager'),
  intro: text('أربط خبرتي في إدارة المخازن وSAP بتحليل البيانات والأتمتة؛ وأحوّل احتياجات العمل إلى برامج وأدوات عملية تدعم دقة المخزون وكفاءة العمليات واتخاذ القرار.', 'I connect hands-on warehouse management and SAP experience with data analysis and automation, turning operational needs into practical software and tools that support inventory accuracy, efficient operations and informed decisions.'),
  specialties: text('SAP MM / EWM / SD | مراقبة المخزون | أتمتة التقارير | رقمنة المخازن', 'SAP MM / EWM / SD | Inventory Control | Reporting Automation | Warehouse Digitization'),
  browse: text('استعراض أعمالي', 'Explore my work'),
  download: text('تحميل السيرة الذاتية', 'Download CV'),
  portrait: text('الصورة الشخصية لأحمد علاء', 'Portrait of Ahmed Alaa'),
  years: text('سنوات من الخبرة التشغيلية', 'Years of operational experience'),
  sites: text('مواقع للعمليات المخزنية', 'Warehouse operational sites'),
  sap: text('خبرة عملية وتكامل بين العمليات', 'Hands-on expertise & process integration'),
  practical: text('خبرة ميدانية تتحول إلى حلول', 'Operational experience, put to work'),
  about: text('إدارة المخازن برؤية أوسع.', 'Warehouse management. A wider perspective.'),
  aboutIntro: text('لدي خبرة تتجاوز 10 سنوات في إدارة المخازن والخدمات اللوجستية، وأدير العمليات عبر 5+ مواقع. أعمل في مؤسسة الإيمان منذ 2016، وتدرّجت من أمين مخزن إلى مشرف ثم مدير مخازن. أجمع بين إدارة العمليات والرقابة على المخزون وتطوير الإجراءات والأدوات الرقمية.', 'With 10+ years in warehouse and logistics operations, I manage operations across 5+ sites. At Aleman Foundation since 2016, I have progressed from Storekeeper to Warehouse Supervisor and Warehouse Manager. My experience combines daily operations, inventory control, better processes and practical digital tools.'),
  aboutFocus: text('أستخدم SAP MM وEWM وSD، مع التنسيق مع PP وPM وFI لربط المخازن بالمشتريات والإنتاج والصيانة والمالية. وأطوّر تقارير ولوحات متابعة باستخدام Excel وGoogle Sheets وVBA لدعم وضوح البيانات والقرار.', 'I work with SAP MM, EWM and SD, coordinating with PP, PM and FI to connect warehouse, procurement, production, maintenance and finance operations. I develop reports and dashboards with Excel, Google Sheets and VBA to make data clearer and decisions better informed.'),
  aboutGbs: text('أقود حاليًا مشروع Global Barcode Solutions (GBS)، من التنسيق مع المورد والتعاقد إلى التنفيذ وإطلاق النظام.', 'I am currently leading the Global Barcode Solutions (GBS) project, from vendor alignment and contracting through implementation and system rollout.'),
  seeGbs: text('مشروع GBS', 'The GBS project'),
  focus: [text('دقة المخزون والرقابة', 'Inventory accuracy & control'), text('تكامل العمليات عبر SAP', 'Connected SAP processes'), text('تحسين الإجراءات والأتمتة', 'Process improvement & automation')],
  workEyebrow: text('برامج طوّرتها لخدمة العمل', 'Software built around real operations'),
  workTitle: text('احتياج عملي. حل رقمي.', 'A real need. A practical solution.'),
  workIntro: text('برنامجان يجسّدان تحويل احتياجات التشغيل إلى شاشات متابعة وتوثيق وتقارير. استعرض وظائفهما ولقطات من الواجهات الفعلية.', 'Two systems that turn operational needs into monitoring, documentation and reporting workflows. Explore their functions and screenshots from the actual interfaces.'),
  details: text('تفاصيل المشروع', 'Project details'),
  role: text('دوري', 'My contribution'),
  need: text('احتياج العمل', 'Operational need'),
  functions: text('الوظائف', 'Functions'),
  value: text('الفائدة التشغيلية', 'Operational value'),
  gallery: text('معرض الشاشات', 'Screen gallery'),
  openGallery: text('استعراض الشاشات', 'Explore screenshots'),
  screens: text('لقطة شاشة', 'screenshots'),
  enlarge: text('تكبير الصورة', 'Enlarge image'),
  previous: text('الصورة السابقة', 'Previous image'),
  next: text('الصورة التالية', 'Next image'),
  close: text('إغلاق المعرض', 'Close gallery'),
  zoom: text('عرض بالحجم الأصلي', 'View at original size'),
  fit: text('ملاءمة الصورة للشاشة', 'Fit image to screen'),
  imageError: text('تعذّر تحميل الصورة. حاول فتحها مرة أخرى.', 'The image could not load. Try opening it again.'),
  privacy: text('حُجبت البيانات الشخصية والتشغيلية الحساسة في الصور المعروضة.', 'Personal and sensitive operational data has been redacted from these images.'),
  digitalEyebrow: text('التحول الرقمي في العمليات', 'Digital transformation in practice'),
  digitalTitle: text('من الإجراءات إلى التتبّع الرقمي.', 'From procedures to digital traceability.'),
  ongoing: text('مشروع جارٍ', 'In progress'),
  gbsSub: text('مشروع رقمنة المخازن بالباركود', 'Warehouse digitization with barcodes'),
  gbsRole: text('مدير المشروع', 'Project Manager'),
  gbsIntro: text('أقود تنفيذ Global Barcode Solutions داخل العمليات المخزنية، بهدف تحسين التتبّع ووضوح المخزون والرقابة التشغيلية.', 'I lead the implementation of Global Barcode Solutions within warehouse operations, with the goal of improving traceability, inventory visibility and operational control.'),
  gbsSteps: [
    { title: text('التنسيق مع المورد', 'Vendor alignment'), body: text('مواءمة احتياجات التشغيل مع متطلبات الحل.', 'Align operational needs with the solution requirements.') },
    { title: text('التعاقد', 'Contracting'), body: text('التنسيق والمتابعة في مرحلة التعاقد.', 'Coordinate and follow through the contracting stage.') },
    { title: text('التنفيذ', 'Implementation'), body: text('قيادة تنفيذ النظام داخل العمليات المخزنية.', 'Lead system implementation within warehouse operations.') },
    { title: text('إطلاق النظام', 'System rollout'), body: text('متابعة إطلاق الحل ضمن دورة العمل.', 'Oversee the solution rollout within the operational workflow.') },
  ],
  reportingTitle: text('تقارير أوضح. عمل يدوي أقل.', 'Clearer reporting. Less manual effort.'),
  reportingBody: text('أطوّر تقارير ولوحات متابعة آلية باستخدام Excel وGoogle Sheets وVBA لتحليل حركة المخزون والاستهلاك والأصناف السريعة والبطيئة الحركة ومؤشرات الأداء. تدعم هذه الأدوات سرعة إعداد التقارير ووضوح البيانات.', 'I develop automated reports and dashboards with Excel, Google Sheets and VBA to analyse stock movements, consumption, slow- and fast-moving items and performance indicators. These tools support faster reporting and clearer operational data.'),
  reportLink: text('شاهد مركز التقارير ضمن أعمالي', 'See the report center in my work'),
  experienceEyebrow: text('الخبرة المهنية', 'Professional experience'),
  experienceTitle: text('مسار بدأ من أرض المخزن.', 'A career built on the warehouse floor.'),
  company: text('مؤسسة الإيمان', 'Aleman Foundation'),
  current: text('الوظيفة الحالية', 'Current role'),
  skillsEyebrow: text('مجالات الخبرة', 'Areas of expertise'),
  skillsTitle: text('التشغيل والبيانات، معًا.', 'Operations and data, together.'),
  learningEyebrow: text('التعليم والتطوير المهني', 'Education & professional development'),
  learningTitle: text('خبرة عملية، وتعلّم مستمر.', 'Practical experience. Continuous learning.'),
  degree: text('بكالوريوس الاقتصاد', 'Bachelor’s Degree in Economics'),
  university: text('جامعة الزقازيق', 'Zagazig University'),
  courses: text('كورسات وشهادات تعلّم مختارة', 'Selected courses & learning certificates'),
  viewCertificate: text('عرض', 'View'),
  downloadCertificate: text('تحميل', 'Download'),
  viewCertificateLabel: text('عرض الشهادة', 'View certificate'),
  downloadCertificateLabel: text('تحميل الشهادة', 'Download certificate'),
  opensInNewTab: text('يفتح في تبويب جديد', 'Opens in a new tab'),
  completion: text('إتمام دورة', 'Course completion'),
  learningPath: text('شهادة مسار تعليمي', 'Learning path certificate'),
  hours: text('96 ساعة · 9.6 CEUs', '96 hours · 9.6 CEUs'),
  trainingNote: text('دورات SAP المعروضة تدريبية؛ لا تمثل اعتمادًا مهنيًا رسميًا من SAP.', 'The SAP courses listed are training courses, rather than official SAP professional certification.'),
  contactEyebrow: text('لنبدأ حوارًا', 'Let’s start a conversation'),
  contactTitle: text('تواصل معي.', 'Get in touch.'),
  contactBody: text('لمناقشة فرص العمل في إدارة المخازن والخدمات اللوجستية أو مشروعات تحسين العمليات والتحول الرقمي.', 'To discuss opportunities in warehouse and logistics management, process improvement or digital transformation projects.'),
  email: text('البريد الإلكتروني', 'Email'),
  phone: text('الهاتف', 'Phone'),
  linkedIn: text('الملف المهني على LinkedIn', 'Professional profile on LinkedIn'),
  location: text('الموقع', 'Location'),
  rights: text('جميع الحقوق محفوظة.', 'All rights reserved.'),
  backTop: text('العودة إلى الأعلى', 'Back to top'),
};
export const projects = [
  {
    id: 'warehouse-audit', key: 'audit', number: '01',
    name: text('WAREHOUSE AUDIT SYSTEM', 'WAREHOUSE AUDIT SYSTEM'),
    category: text('مراجعة المخزون والتقارير', 'Inventory review & reporting'),
    summary: text('برنامج يجمع مراجعة الحركات المخزنية والجرد والتوثيق والتقارير في واجهة واحدة، مع شاشات متابعة تناسب الكمبيوتر والهاتف.', 'A system bringing stock movement review, inventory auditing, documentation and reporting into one interface, with desktop and mobile views.'),
    need: text('تجميع التقارير ومراجعة البيع والتحويلات والوارد والخامات، وتوثيق الجرد ومتابعة فروقه من مساحة عمل منظمة.', 'Bring reports together, review sales, transfers, receipts and materials, and document inventory counts and their differences in an organised workspace.'),
    role: text('طوّرت البرنامج لتحويل احتياجات مراجعة المخازن إلى أدوات عملية لرفع التقارير، ومراجعة البيانات، والتوثيق والمتابعة.', 'I developed the system to turn warehouse review needs into practical tools for report uploads, data review, documentation and monitoring.'),
    features: [text('مركز رفع التقارير وسجل النسخ المرفوعة', 'Report upload center and uploaded report history'), text('مراجعة البيع والتحويلات والوارد', 'Sales, transfers and incoming stock review'), text('متابعة الخامات والجرد وفروق الجرد', 'Material tracking, inventory counts and count differences'), text('تقارير تنفيذية ولوحات متابعة وتصدير', 'Executive reports, dashboards and exports'), text('المتابعة الإدارية وإدارة المستخدمين والصلاحيات', 'Team administration, users and permissions management'), text('واجهات للهاتف ومظهر فاتح وداكن', 'Mobile views, with light and dark appearances')],
    value: text('يوفّر نقطة واضحة لمراجعة البيانات وتوثيق الجرد ومتابعة التقارير، بما يدعم الرقابة التشغيلية واتخاذ القرار.', 'Provides a clear place to review data, document inventory counts and monitor reports, supporting operational control and decision-making.'),
    preview: './assets/audit-02-dark.webp',
    previewCaption: text('لوحة المتابعة الرئيسية', 'Main dashboard'),
    tags: [text('الجرد والتوثيق', 'Inventory documentation'), text('لوحات متابعة', 'Dashboards'), text('تقارير وتصدير', 'Reports & exports')],
  },
  {
    id: 'custody-management', key: 'custody', number: '02',
    name: text('برنامج إدارة العهدة', 'Custody Management System'),
    category: text('تتبّع العهدة والحركات', 'Custody & movement tracking'),
    summary: text('برنامج لتوثيق صرف العهدة واستلامها، ومتابعة حالتها وحركاتها، مع شاشات للموظفين والمقاولين والتقارير.', 'A system for documenting custody issues and returns, tracking their status and movements, with workflows for employees, contractors and reporting.'),
    need: text('تنظيم صرف العهدة واستلامها للموظفين والمقاولين، والرجوع إلى سجلات الحركة والتقارير من برنامج واحد.', 'Organise custody issues and returns for employees and contractors, with movement records and reports available in one system.'),
    role: text('طوّرت البرنامج لتنظيم دورة العهدة من التكويد والصرف إلى الاستلام وسجل الحركات والتقارير.', 'I developed the system to organise the custody lifecycle, from coding and issue through returns, movement records and reports.'),
    features: [text('صرف لموظف بكود أو دون كود', 'Issue to employees with or without a code'), text('صرف لمقاول عن طريق وسيط', 'Issue to contractors through an intermediary'), text('استلام العهدة ومتابعة حالتها', 'Custody returns and status monitoring'), text('تقارير وسجل للحركات', 'Reports and a movement log'), text('تكويد الأصناف والموظفين', 'Item and employee coding'), text('التنقل بين المواقع وإدارة المستخدمين والصلاحيات', 'Site navigation, users and permissions management')],
    value: text('يدعم وضوح العهدة المصروفة والمستلمة، ويوفّر سجلًا للحركات يساعد على المتابعة والرجوع إلى البيانات.', 'Supports visibility of issued and returned custody items, with movement records for follow-up and reference.'),
    preview: './assets/custody-02.webp',
    previewCaption: text('لوحة المتابعة ودورة العهدة', 'Dashboard & custody workflows'),
    tags: [text('صرف واستلام', 'Issues & returns'), text('سجل الحركات', 'Movement log'), text('متابعة وتقارير', 'Tracking & reporting')],
  },
];
export const experience = [
  { period: text('مايو 2019 – حتى الآن', 'May 2019 – Present'), title: text('مدير مخازن | استشاري SAP MM (التنفيذ الداخلي)', 'Warehouse Manager | SAP MM Consultant (Internal Implementation)'), current: true,
    items: [text('إدارة الاستلام والصرف والتخزين والرقابة على المخزون عبر 5+ مواقع، وتصميم مواقع التخزين وBins وMovement Types.', 'Manage receiving, issuing, storage and inventory control across 5+ sites, with warehouse structure, bins, locations and movement types.'), text('SAP Key User لوحدات MM وEWM وSD، مع التنسيق مع PP وPM وFI ودورة المشتريات PR / PO / GR.', 'SAP Key User for MM, EWM and SD, coordinating with PP, PM and FI and the PR / PO / GR procurement cycle.'), text('قيادة الفريق، ومتابعة الجرد ومؤشرات الأداء، وتطوير التقارير والأتمتة وقيادة مشروع الباركود.', 'Lead the team, monitor inventory counts and KPIs, develop reports and automation, and lead the barcode project.')] },
  { period: text('مايو 2017 – مايو 2019', 'May 2017 – May 2019'), title: text('مشرف مخازن', 'Warehouse Supervisor'), current: false,
    items: [text('الإشراف على العمليات اليومية وتنسيق أعمال فريق المخازن وتحسين سير العمل.', 'Supervise daily warehouse operations, coordinate team activities and improve workflow.'), text('إدارة المخزون وحركاته والتقارير باستخدام Alpha.', 'Manage inventory, stock movements and reporting using Alpha.')] },
  { period: text('مايو 2016 – مايو 2017', 'May 2016 – May 2017'), title: text('أمين مخزن', 'Storekeeper'), current: false,
    items: [text('تنفيذ الاستلام والصرف وحفظ سجلات المخزون باستخدام Alpha.', 'Handle receiving and issuing, maintaining accurate stock records with Alpha.'), text('ضمان التخزين السليم والمناولة والانضباط في العمل اليومي.', 'Ensure proper storage, material handling and day-to-day warehouse discipline.')] },
];
export const skills = [
  { icon: 'warehouse', title: text('إدارة المخازن ومراقبة المخزون', 'Warehouse & inventory management'), items: text('الاستلام والصرف · الجرد الدوري · دقة الأرصدة · تخطيط المخازن وBins', 'Receiving & issuing · Cycle counting · Stock accuracy · Warehouse layout & bins') },
  { icon: 'network', title: text('SAP والتكامل بين العمليات', 'SAP & process integration'), items: text('SAP MM / EWM / SD · SAP Key User · التنسيق مع PP / PM / FI', 'SAP MM / EWM / SD · SAP Key User · PP / PM / FI coordination') },
  { icon: 'clipboard', title: text('دورة المشتريات', 'Procurement cycle'), items: text('PR / PO / GR · التنسيق مع المشتريات والمالية · توافر المواد', 'PR / PO / GR · Purchasing & finance coordination · Material availability') },
  { icon: 'chart', title: text('تحليل البيانات والتقارير', 'Data analysis & reporting'), items: text('مؤشرات الأداء · تحليل الحركة والاستهلاك · الأصناف السريعة والبطيئة الحركة', 'KPIs · Movement & consumption analysis · Slow- & fast-moving items') },
  { icon: 'sheet', title: text('Excel والأتمتة', 'Excel & automation'), items: text('Excel · Pivot Tables · Lookup Functions · Google Sheets · VBA · التحقق من البيانات', 'Excel · Pivot Tables · Lookup Functions · Google Sheets · VBA · Data validation') },
  { icon: 'code', title: text('تطوير الأدوات التشغيلية', 'Operational tools development'), items: text('تحويل احتياجات العمل إلى برامج عملية · نماذج توثيق · لوحات متابعة', 'Turn operational needs into practical software · Documentation workflows · Dashboards') },
  { icon: 'barcode', title: text('الباركود والتحول الرقمي', 'Barcode & digitization'), items: text('Global Barcode Solutions · التتبّع · وضوح المخزون · إطلاق النظام', 'Global Barcode Solutions · Traceability · Inventory visibility · System rollout') },
  { icon: 'users', title: text('القيادة وتحسين الإجراءات', 'Leadership & process improvement'), items: text('قيادة الفرق · توزيع المهام · التنسيق مع الموردين · التعاون بين الإدارات', 'Team supervision · Task allocation · Vendor coordination · Cross-functional collaboration') },
];
export type Course = { name: string; provider: string; date?: Text; type: 'path' | 'course'; hours?: boolean; certificate?: string };
export const courses: Course[] = [
  { name: 'CSCMP Supply Chain Foundations: Inventory Management Professional Certificate', provider: 'CSCMP / LinkedIn Learning', date: text('أكتوبر 2026', 'Oct 2026'), type: 'path', certificate: './assets/certificates/cscmp-inventory-management.pdf' },
  { name: 'BUS606: Operations and Supply Chain Management', provider: 'Saylor University', date: text('سبتمبر 2026', 'Sep 2026'), type: 'course', hours: true, certificate: './assets/certificates/bus606-operations-supply-chain-management.pdf' },
  { name: 'SAP Materials Management Essential Training', provider: 'LinkedIn Learning', date: text('سبتمبر 2026', 'Sep 2026'), type: 'course', certificate: './assets/certificates/sap-materials-management-essential-training.pdf' },
  { name: 'SAP S/4HANA Essential Training', provider: 'LinkedIn Learning', type: 'course', certificate: './assets/certificates/sap-s4hana-essential-training.pdf' },
  { name: 'Supply Chain Foundations: Analytics', provider: 'LinkedIn Learning', date: text('أكتوبر 2026', 'Oct 2026'), type: 'course', certificate: './assets/certificates/supply-chain-foundations-analytics.pdf' },
  { name: 'Excel Supply Chain Analysis: Solving Inventory Problems', provider: 'LinkedIn Learning', type: 'course', certificate: './assets/certificates/excel-supply-chain-inventory-problems.pdf' },
  { name: 'Inventory Management Foundations', provider: 'LinkedIn Learning', type: 'course', certificate: './assets/certificates/inventory-management-foundations.pdf' },
  { name: 'Foundations of Working Capital Management', provider: 'LinkedIn Learning', type: 'course', certificate: './assets/certificates/working-capital-management-foundations.pdf' },
];
